version: '3.9'

volumes:
  mssql-data:
    external: true

services:
  
  mssql-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root
    environment: 
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=P@ssw0rd
    ports: 
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql/data

  api:
    image: api
    environment:
      - DB_CONNECTION=Server=mssql-db;Initial Catalog=Ticket;user Id=SA;password=P@ssw0rd
    build:
      context: .
      dockerfile: Service/Api/Dockerfile
    ports:
      - "5252:80"
    depends_on:
      - mssql-db

  web:
    image: web
    environment:
      - ApiUrl=http://api
    build:
      context: .
      dockerfile: Web/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - api
    